---
title: "PRA2_yolanda67_analysis: Anàlisi de dades"
author: "Yolanda Sánchez"
date: "8 Gener de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

******
## Preparació entorn
******

* Versión de R instalada: 3.4.1
```{r Label_0100, eval=TRUE, echo=TRUE, warning=FALSE }

# Establecer directorio de trabajo
setwd("C:/UOC/Màster Data Science/semestre-1/Tipologia i cicle de vida de les dades/Bloc 3/Practica 2/src")

```

* Càrrega de llibreries 

```{r Label_LoadLibraries, eval=TRUE, echo=TRUE, warning=FALSE }

require(dplyr)
require(R.utils)
library(ggplot2)
library(corrplot)

```

## Estadístiques bàsiques


```{r Label_BasicsStats, eval=TRUE, echo=TRUE, warning=FALSE }

#Càrrega del fitxer principal (title.basics)
df <- read.csv(file="MoviesInfo2.tsv", header=TRUE, sep="\t", quote="\"", fill=TRUE, stringsAsFactors=FALSE)
print(paste("Nombre d'observacions:",nrow(df)))

#Creació Dataframe per estadístiques relacionades amb Pressupost (budget) i Recaptació (Revenue)
df_revenue_budget <- subset(df, revenue>0 & budget>0)

print(paste("Mean:",mean(df_revenue_budget$revenue)))
print(paste("Median:",median(df_revenue_budget$revenue)))
print(paste("Median (elimina 10% valors extrems):",median(df_revenue_budget$revenue,trim=0.1)))
print(paste("Variance:",var(df_revenue_budget$revenue)))
print(paste("Standard Deviation:",sd(df_revenue_budget$revenue)))

summary(df_revenue_budget$revenue);

#Histograma de Recaptació
hist(df_revenue_budget$revenue, main="Recaptació", xlab="revenue", col="green", breaks=6);
lines(density(df_revenue_budget$revenue));

hist(df_revenue_budget$revenue, main="Recaptació",  
     xlab="revenue", 
     border="blue", 
     col="green", 
     las=0.5, 
     breaks=6, 
     prob = TRUE);
lines(density(df_revenue_budget$revenue));

```

```{r Label_Correlation, eval=TRUE, echo=TRUE, warning=FALSE }

#Volem veure si hi ha correlació entre la recaptació (revenue) i el pressupost (budget)
M <- data.frame(df_revenue_budget$revenue, df_revenue_budget$budget)
print(cor(df_revenue_budget$budget, df_revenue_budget$revenue))
corrplot(cor(M), method="ellipse")
plot(df_revenue_budget$budget, df_revenue_budget$revenue, xlab="Budget", ylab="Revenue")

```

```{r Label_GeneresDecada, eval=TRUE, echo=TRUE, warning=FALSE }

#Recupera lista de gèneres
genres <- data.frame(unique(df[,4]), stringsAsFactors = FALSE)
dfg <- read.table(text = "", colClasses = c("character"), col.names = c("genre"));
g<-c("genre")
for (row in genres)
{
  g <- c(g,unlist(strsplit(as.character(row),",")))
}
genres<-unique(g)

#df_byGenreDecade = group_by(df, genres, (releaseYear %/% 10) * 10)
df_byGenreDecade = group_by(df, mainGenre, releaseYear)
df_byGenreDecade <- summarize(df_byGenreDecade, total.count=n())
names(df_byGenreDecade)[2]<-"decade"
print(df_byGenreDecade)

ggplot(df_byGenreDecade, aes(x = mainGenre, y = decade, fill = mainGenre)) + geom_boxplot() + ggtitle("Distribució de pel·lícules per Gènere/Dècada")

```

